version: 2.1

jobs:
  update-locale:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.02-20.04
    steps:
      - checkout:
          path: ~/app
      - run: echo "Updated locale..." > locales
      - persist_to_workspace:
          root: .
          paths:
            - locales

  build-android:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.02-20.04
    steps:
      - checkout:
          path: ~/app
      - attach_workspace:
          at: /tmp/prev
      - run: find /tmp/locale -type f -exec cat {} \;
      - run: echo "Android Build" > android/1
      - persist_to_workspace:
          root: android
          paths:
            - android/*

  build-ios:
    docker:
      - image: cimg/base:2022.02-20.04
    steps:
      - checkout:
          path: ~/app
      - run: echo "iOS Building..."
  
  release:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.02-20.04
    steps:
      - checkout
      - checkout:
          path: ~/app
      - attach_workspace:
          at: /tmp/prev
      - run: echo "Releasing"
      - run: ls -lR /tmp/prev
      - run: find /tmp/prev -type f -exec cat {} \;

workflows:
  version: 2
  test:
    jobs:
      - hold:
          type: approval
          filters:
            tags:
               only: /^(?!v).*/
            branches:
              ignore: /.*/
      - update-locale:
          requires:
            - hold
          filters:
            tags:
               only: /^(?!v).*/
            branches:
              ignore: /.*/
      - build-android:
          requires:
            - update-locale
          filters:
            tags:
               only: /^(?!v).*/
            branches:
              ignore: /.*/
      - build-ios:
          requires:
            - update-locale
          filters:
            tags:
               only: /^(?!v).*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build-ios
            - build-android
          filters:
            tags:
               only: /^(?!v).*/
            branches:
              ignore: /.*/
