version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.02-20.04
    steps:
      - checkout
      - run: echo "Testing..."

workflows:
  test:
    jobs:
      - build:
          filters:
            tags:
               only: /^(?!v).*/
